# Generated by Django 5.1.7 on 2025-04-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
