# Generated by Django 5.1.7 on 2025-04-09 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_product_created_date_remove_product_image_and_more'),
        ('products', '0006_alter_product_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='api.customuser'),
        ),
    ]
